### ISSUE TITLE
RuntimeWarning: Setting standard icon failed

### ISSUE THREAD

**Issue by wfx** [DaveMDS/edone#2]
WIth 1.14 libs i get:

Traceback (most recent call last):
  File "/usr/bin/edone", line 6, in <module>
    sys.exit(main())
  File "/usr/lib/python3.4/site-packages/edone/main.py", line 43, in main
    win = EdoneWin()
  File "/usr/lib/python3.4/site-packages/edone/gui.py", line 117, in **init**
    b.content = Icon(hbox1, standard='add')
  File "efl/elementary/icon.pyx", line 227, in efl.elementary.icon.Icon.**init** (efl/elementary/icon.c:2084)
  File "efl.evas_object.pxi", line 209, in efl.evas.Object._set_properties_from_keyword_args (efl/evas/efl.evas.c:51432)
  File "efl.eo.pyx", line 272, in efl.eo.Eo._set_properties_from_keyword_args (efl/eo/efl.eo.c:3275)
  File "efl/elementary/icon.pyx", line 298, in efl.elementary.icon.Icon.standard.__set__ (efl/elementary/icon.c:2681)
RuntimeWarning: Setting standard icon failed

**Comment by mwarchulinski** [comment]
I don't have the issue with 1.14.0. Maybe the issue is for the 1.14.99 version of elementary ? Can you confirm it ?

**Comment by wfx** [comment]
Hi,
yes right. I have found a  (forgotten installed) elementary_test 1.14.99.
I remove it and now works :)
