### ISSUE TITLE
cannot launch edone binary

### ISSUE THREAD

**Issue by Yomi0** [DaveMDS/edone#3]
I think this might be due to the fact that python-efl fails to build on my system.
Here's the output I get after running `python setup.py install --user`

```
[05:21:01 | yomi@xana ~/software/edone] » python setup.py install --user
running install
running build
running build_py
running build_scripts
running install_lib
running install_scripts
changing mode of /home/yomi/.local/bin/edone to 755
running install_data
running install_egg_info
Removing /home/yomi/.local/lib/python3.4/site-packages/edone-0.9-py3.4.egg-info
Writing /home/yomi/.local/lib/python3.4/site-packages/edone-0.9-py3.4.egg-info

[05:21:09 | yomi@xana ~/software/edone] » cd bin

[05:21:12 | yomi@xana ~/software/edone/bin] » ./edone
Traceback (most recent call last):
  File "./edone", line 4, in <module>
    from edone.main import main
  File "/home/yomi/.local/lib/python3.4/site-packages/edone/main.py", line 26, in <module>
    from efl import elementary as elm
  File "/usr/lib/python3.4/site-packages/efl/elementary/__init__.py", line 19, in <module>
    from efl.elementary.general import *
ImportError: /usr/lib/python3.4/site-packages/efl/elementary/general.cpython-34m.so: undefined symbol: AnnotateIgnoreReadsBegin
```

possibly related : https://phab.enlightenment.org/T2493

Arch Linux

Name : efl-git
Version : 1.14.99.30953.88cb6b7-1
Build Date : Fri 12 Jun 2015 02:48:25 PM EDT
Install Date : Fri 12 Jun 2015 02:50:01 PM EDT

Name : elementary-git
Version : 1.14.99.11541.ga17116e-1
Build Date : Fri 12 Jun 2015 02:57:57 PM EDT
Install Date : Fri 12 Jun 2015 02:59:10 PM EDT

**Comment by Yomi0** [comment]
Built python-efl from git. Problem solved. 
Sorry for the noise.
